### ISSUE TITLE
Translatable ?

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [MaximillianLeonov/Musicmax#145]
Is the app translatable and when, where are the strings to translate ?
Thanks in advance.

**Comment by MaximillianLeonov** [comment]
Hi. Since this application is modularized, the string resources are located in the resources of the corresponding modules.

At the moment, you can find string resources in these paths:
- [app/src/main/res/values/strings.xml](https://github.com/MaximillianLeonov/Musicmax/blob/main/app/src/main/res/values/strings.xml)
- [core/core-designsystem/src/main/res/values/strings.xml](https://github.com/MaximillianLeonov/Musicmax/blob/main/core/core-designsystem/src/main/res/values/strings.xml)
- [core/core-ui/src/main/res/values/strings.xml](https://github.com/MaximillianLeonov/Musicmax/blob/main/core/core-ui/src/main/res/values/strings.xml)
- [core/core-permission/src/main/res/values/strings.xml](https://github.com/MaximillianLeonov/Musicmax/blob/main/core/core-permission/src/main/res/values/strings.xml)
- [core/core-media-common/src/main/res/values/strings.xml](https://github.com/MaximillianLeonov/Musicmax/blob/main/core/core-media-common/src/main/res/values/strings.xml)
- [core/core-media-notification/src/main/res/values/strings.xml](https://github.com/MaximillianLeonov/Musicmax/blob/main/core/core-media-notification/src/main/res/values/strings.xml)
- [features/feature-home/src/main/res/values/strings.xml](https://github.com/MaximillianLeonov/Musicmax/blob/main/features/feature-home/src/main/res/values/strings.xml)
- [features/feature-search/src/main/res/values/strings.xml](https://github.com/MaximillianLeonov/Musicmax/blob/main/features/feature-search/src/main/res/values/strings.xml)
- [features/feature-favorite/src/main/res/values/strings.xml](https://github.com/MaximillianLeonov/Musicmax/blob/main/features/feature-favorite/src/main/res/values/strings.xml)
- [features/feature-settings/src/main/res/values/strings.xml](https://github.com/MaximillianLeonov/Musicmax/blob/main/features/feature-settings/src/main/res/values/strings.xml)
- [features/feature-player/src/main/res/values/strings.xml](https://github.com/MaximillianLeonov/Musicmax/blob/main/features/feature-player/src/main/res/values/strings.xml)
- [features/feature-artist/src/main/res/values/strings.xml](https://github.com/MaximillianLeonov/Musicmax/blob/main/features/feature-artist/src/main/res/values/strings.xml)
- [features/feature-album/src/main/res/values/strings.xml](https://github.com/MaximillianLeonov/Musicmax/blob/main/features/feature-album/src/main/res/values/strings.xml)
- [sync/work/src/main/res/values/strings.xml](https://github.com/MaximillianLeonov/Musicmax/blob/main/sync/work/src/main/res/values/strings.xml)

**Comment by mondlicht-und-sterne** [comment]
@MaximillianLeonov 

Thanks for the quick answer.

Do I have to translate all these files per language ?

**Comment by MaximillianLeonov** [comment]
@mondlicht-und-sterne,

As far as I know, there is currently no easy out-of-the-box solution to do this other than like this.

**Comment by mondlicht-und-sterne** [comment]
@MaximillianLeonov 

Do you know Weblate ?
I recommend [https://translate.codeberg.org/](https://translate.codeberg.org/)
I translate a lot there.

**Comment by MaximillianLeonov** [comment]
@mondlicht-und-sterne,

Thanks for the suggestion. I have checked out some services and decided to use Crowdin. So, I integrated Crowdin into the project. It is available on Crowdin at [this link](https://crowdin.com/project/musicmax-android).
